
server:
  port: 8081
 
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/neusoft
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.neusoft.oa.hr.model
 
#showSql
logging:
  level:
    com.neusoft.oa.hr.mapper: debug
